# Generated by Django 5.1.3 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodon_main', '0002_mood_alter_forum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
